default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: memknow_development
  username: memknow
  password: memknow!
  host: localhost

test:
  <<: *default
  database: memknow_test

production:
  <<: *default
  database: memknow_development
